server:
  port: 8083
spring:
  application:
    name: leyou-search
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.206.129:9300
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-expiration-duration-in-seconds: 10 #10秒不发送就过期
    lease-renewal-interval-in-seconds: 5 #每隔5秒发送一次心跳